# Generated by Django 5.2.1 on 2025-06-22 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_url',
            new_name='url',
        ),
    ]
